### PR TITLE
Feat angular

### PR DESCRIPTION
**Pull request by p3tuh**

### CODE REVIEW

**Comment by dsernst** [comment]
looks good!

**Comment by dsernst** [comment]
How should I install client's dependencies? I see the links to `/lib/` and `/dist/` folders but looks like they were `.gitignore`'d. Were these from `bower install`? Grunt? Manually pulled in?

**Comment by p3tuh** [comment]
They were manually pulled in. I'll clean up a bit and remove the dist from the gitignore file for the next pull.

**Comment by dsernst** [comment]
k thanks!

**Pull request merged**
